#### general settings
name: AGCM_v1
use_tb_logger: true
model: sr
distortion: sr
scale: 1
gpu_ids: [0]

#### network structures
network_G:
  which_model_G: ConditionNet
  classifier: color_condition 
  cond_c: 6

#### datasets
datasets:
  train:
    name: HDRTV1K_train
    mode: LQGT_rcan
    dataroot_GT: ../hyconditm-master/datasets/HDRTV1K/train/train_hdr_sub
    dataroot_LQ: ../hyconditm-master/datasets/HDRTV1K/train/train_sdr_sub
    dataroot_cond: ../hyconditm-master/datasets/HDRTV1K/train_cond
    # dataroot_GT: dataset/DIV2K_scale_sub/GT
    # dataroot_LQ: dataset/DIV2K_scale_sub/LR
    cond_scale: 4
    use_shuffle: true
    n_workers: 0 # per GPU
    batch_size: 8
    GT_size: 480
    use_flip: false
    use_rot: false
    color: RGB
  val:
    name: HDRTV1K_test
    mode: LQGT_rcan
    dataroot_GT: /root/autodl-tmp/hyconditm-master/datasets/HDRTV1K/test/test_hdr_1080p
    dataroot_LQ: /root/autodl-tmp/hyconditm-master/datasets/HDRTV1K/test/test_sdr_1080p
    dataroot_cond: ../hyconditm-master/datasets/HDRTV1K/cond
    use_shared_memory: false
    cond_scale: 4
    # dataroot_GT: dataset/DIV2K_valid_sub/GT
    # dataroot_LQ: dataset/DIV2K_valid_sub/LR

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 500000
  warmup_iter: -1  # no warm up
  T_period: [500000]
  restarts: [500000]
  restart_weights: [1]
  eta_min: !!float 1e-7
  lr_gamma: 0.5
  clear_state: 1000000

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: 10000

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: 20000
